version: '3.8'

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
            - static_volume:/app/backend/static
    server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        command: >
            sh -c "python manage.py collectstatic --noinput &&
            gunicorn core.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4"
        volumes:
            - static_volume:/app/backend/static
            - ./db:/db
            - ./backend/:/app
        expose:
            - 8000
        env_file:
            - ./.env
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine
        expose:
            - 6379
    celery:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        command: celery -A core worker -l info
        volumes:
            - ./db:/db
            - ./backend/:/app
        env_file:
            - ./.env
        depends_on:
            - redis
    celery-beat:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        command: celery -A core beat -l info
        volumes:
            - ./db:/db
            - ./backend/:/app
        env_file:
            - ./.env
        depends_on:
            - redis
volumes:
    static_volume: {}