# Generated by Django 5.0.6 on 2024-07-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_alter_link_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-id', 'url'), 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterField(
            model_name='link',
            name='status_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='status code'),
        ),
    ]
